apiVersion: batch/v1
kind: Job
metadata:
  name: part-jc-test-pretrained
spec:
  template:
    metadata:
      labels:
        mount-eos: "true"
        mount-cvmfs: "true"
        home: "eos"
        mount-afs: "true"
    spec:
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
      containers:
      - name: part-jc-test-pretrained
        image: registry.cern.ch/ngt/pytorch:2.3.1
        command:
        - "bash"
        - "-c"
        - |
          source /eos/home-m/majorgen/miniconda3/etc/profile.d/conda.sh &&
          conda activate torch_env &&
          cd /eos/home-m/majorgen/particle_transformer &&
          OUTDIR=/eos/home-m/majorgen/particle_transformer/testing/JetClass/pretrained_$(date +%Y%m%d_%H%M) &&
          mkdir -p $OUTDIR &&
          weaver \
            --predict \
            --data-test "/eos/home-m/majorgen/particle_transformer/datasets/JetClass/Pythia/test_20M/*.root" \
            --data-config /eos/home-m/majorgen/particle_transformer/data/JetClass/JetClass_full.yaml \
            --network-config /eos/home-m/majorgen/particle_transformer/networks/example_ParticleTransformer.py \
            --model-prefix /eos/home-m/majorgen/particle_transformer/models/ParT_full.pt \
            --predict-output $OUTDIR/pred.root \
            --num-workers 0 \
            --gpus 0 \
            2>&1 | tee $OUTDIR/test.log
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never