backend: null
batch_size: 128
copy_inputs: false
cross_validation: null
data_config: /eos/home-m/majorgen/particle_transformer/data/JetClass/JetClass_full.yaml
data_fraction: 1
data_test: []
data_train:
- /eos/home-m/majorgen/particle_transformer/datasets/JetClass/Pythia/train_100M/*.root
data_val:
- /eos/home-m/majorgen/particle_transformer/datasets/JetClass/Pythia/val_5M/*.root
demo: false
exclude_model_weights: null
export_onnx: null
extra_selection: null
extra_test_selection: null
fetch_by_files: false
fetch_step: 0.01
file_fraction: 1
freeze_model_weights: null
gpus: '0'
in_memory: false
io_test: false
load_epoch: null
load_model_weights: /eos/home-m/majorgen/particle_transformer/models/ParT_full.pt
local_rank: null
log: logs/train.log
lr_finder: null
lr_scheduler: flat+decay
model_prefix: /eos/home-m/majorgen/particle_transformer/pquant_experiments/results/net
network_config: /eos/home-m/majorgen/particle_transformer/networks/ParticleTransformerWrapper_pquant.py
network_option: []
no_remake_weights: false
num_epochs: 20
num_workers: 0
onnx_opset: 15
optimizer: ranger
optimizer_option: []
predict: false
predict_gpus: null
predict_output: null
print: false
profile: false
regression_mode: false
samples_per_epoch: null
samples_per_epoch_val: null
start_lr: 0.001
steps_per_epoch: 50000
steps_per_epoch_val: 10000
tensorboard: pquant_dst_run7
tensorboard_custom_fn: null
train_val_split: 0.8
use_amp: false
warmup_steps: 0
